spring.application.name=whowantstobeamillionaire
spring.datasource.url=jdbc:sqlite:/Users/kamolotova/Desktop/java/whowantstobeamillionaire/src/main/resources/questions.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1